# Generated by Django 5.0.6 on 2024-05-14 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Event Name')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Event Description')),
                ('organization', models.CharField(blank=True, max_length=100, verbose_name='Organization Name')),
                ('primery_contact', models.CharField(blank=True, max_length=100, verbose_name='Primary Contact')),
                ('alternate_contact', models.CharField(blank=True, max_length=100, verbose_name='Other person')),
                ('hide_names', models.BooleanField(blank=True, default=False, verbose_name='Keep names private')),
                ('reminder_days', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default=7, max_length=2, verbose_name='Days to remind in advance')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
