# Generated by Django 5.0.6 on 2024-05-14 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200, verbose_name='Event Name')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Event Description')),
                ('start_time', models.DateTimeField(verbose_name='Start')),
                ('end_time', models.DateTimeField(verbose_name='End')),
                ('volunteer', models.CharField(max_length=100, verbose_name='Event Name')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
            ],
        ),
    ]
