# Generated by Django 5.0.6 on 2024-05-15 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='alternate_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Alt Contact'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hide_names',
            field=models.BooleanField(blank=True, default=False, verbose_name='Hide Volunteer Names'),
        ),
        migrations.AlterField(
            model_name='event',
            name='reminder_days',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default=7, max_length=5, verbose_name='Days to remind in advance'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Event Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='events.event'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=200, verbose_name='Task Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='volunteer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Volunteer'),
        ),
    ]
