# Generated by Django 5.0.6 on 2024-05-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_task_task_date_alter_task_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time '),
        ),
    ]
